#!/bin/sh
echo "Choose 1 or 2:"
echo "1 for Quench with Wilson gauge action"
echo "2 for Quench with 1x1+1x2 improved gauge action"
read flag
if [ "$flag" -eq "1" ]
then
	cp ../INCLUDE/para_geometry_QW ../INCLUDE/para_geometry 
	cp ./Makefile_Wilson Makefile
	cp ./update.f_Wilson update.f
fi
if [ "$flag" -eq "2" ]
then
	cp ../INCLUDE/para_geometry_QI ../INCLUDE/para_geometry 
	cp ./Makefile_Improve Makefile
	cp ./update.f_Improve update.f
fi
