#!/bin/sh
echo "Choose 1 or 2:"
echo "1 for HMC with Wilson gauge action"
echo "2 for HMC with 1x1+1x2 improved gauge action"
read flag
if [ "$flag" -eq "1" ]
then
	cp ../INCLUDE/para_geometry_HW ../INCLUDE/para_geometry 
	cp hmc.f_GaugeWilson hmc.f
	cp main.f_GaugeWilson main.f
fi
if [ "$flag" -eq "2" ]
then
	cp ../INCLUDE/para_geometry_HI ../INCLUDE/para_geometry 
	cp hmc.f_GaugeImprove hmc.f
	cp main.f_GaugeImprove main.f
fi
